config/routes.rb
Bookdrive::Application.routes.draw do

  match 'staff' => 'pages#staff', :as => :staff
  match 'staff' => 'pages#staff', :as => 'user_root'

  scope "/staff" do
    resources :snippets
    resources :schools
    resources :books do
      resources :copies
      collection do
        get 'update_wishlist'
      end
    end

    devise_for :users, :path => '', :path_names => { :sign_in => 'login', :sign_out => 'logout' }
    resources :users
  
    resources :gifts
    resources :download_events
    resources :donors
    resources :articles
    resources :questions
  
  end

  resources :donors do
    resources :gifts do
      member do
        get 'download'
      end
    end
    member do
      get 'downloads'
      get 'download_tracks'
    end
    collection do
      get 'register'
      post 'submit_registration'
    end
  end

  match 'library' => 'pages#library', :as => :library
  match 'offsite' => 'pages#offsite', :as => :offsite
  match 'oops' => 'pages#oops', :as => :oops
  match 'cookies_required' => 'pages#cookies_required', :as => :cookies_required
  match 'press' => 'pages#press', :as => :press
  match 'thankyou' => 'pages#thankyou', :as => :thankyou
  match 'usedbooks' => 'pages#usedbooks', :as => :usedbooks
  match 'about' => 'pages#about', :as => :about
  match 'faq' => 'pages#faq', :as => :faq
  match '' => 'pages#home', :as => :home
  root :to => 'pages#home'
  

end

app/models/donor.rb
class Donor < ActiveRecord::Base
  has_many :download_events
  
  validates_presence_of :order_number, :message => "You must enter your order number before submitting the form!"
  validates_format_of :order_number, :with => /\A(?:\d{3}-?\d{7}-?\d{7}|[A-Z0-9]{17})\Z/, :message => "Oops! This is not a valid order number. Try to copy and paste it from your confirmation email again."
  validates_uniqueness_of :order_number, :message => "I'm sorry, the order number you entered has already been used on another computer. If you believe this is an error, please email us at richmondbookdrive@gmail.com."

#  validates_presence_of :full_name, :if => :should_validate_address?
#  validates_format_of :full_name, :with => /\A\w+\s\w+\Z/, :if => :should_validate_address?

#  validates_presence_of :address1, :if => :should_validate_address?
#  validates_presence_of :city, :if => :should_validate_address?
#  validates_presence_of :state, :if => :should_validate_address?
#  validates_presence_of :zip, :if => :should_validate_address?
#  validates_format_of :zip, :with => /\A\d{5}(-\d{4})?\Z/, :if => :should_validate_address?

  has_friendly_id :order_number
#  attr_accessor :saving_address
  
  before_create :format_order_number, :generate_donor_code

#  def should_validate_address?
#    saving_address || self.cd_requested?
#  end
  
  def self.search(search)
    if search
      where('order_number ILIKE ?', "%#{search}%")
    else
      scoped
    end
  end

  private
  
  def generate_donor_code
    time = Time.now.to_i.to_s(16).upcase
    self.donor_code = Digest::MD5.hexdigest("#{self.order_number}#{time}")
  end
  
  def format_order_number
    if ( self.order_number !~ /-\d+-/ && self.order_number !~ /[A-Z]/ )
      self.order_number.sub!(/(\d{3})-?(\d{7})-?(\d{7})/, '\1-\2-\3')
    end
  end
  
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  filter_access_to :all

  before_filter :confirm_donor, :only => [:downloads, :download_tracks]

  before_filter :cleanse_order_number, :only => [:submit_registration, :create]

  cache_sweeper :donor_sweeper
  
  helper_method :sort_column, :sort_direction
  
  
  # GET /donors
  # GET /donors.xml
  def index
    @donors = Donor.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 25, :page => params[:page])
  end

  # GET /donors/1
  # GET /donors/1.xml
  def show
    @donor = Donor.find_by_order_number(params[:id])
  end

  # GET /donors/new
  # GET /donors/new.xml
  def new
    @donor = Donor.new
  end
  
  def downloads
    
  end

  def download_tracks
    
  end


  # GET /donors/register
  # GET /donors/register.xml
  def register
    @donor = Donor.new
    
  end


  # GET /donors/1/edit
  def edit
    @donor = Donor.find_by_order_number(params[:id])
  end


  def submit_registration
    @donor = Donor.new(params[:donor])
    
    # Test for Cookies Disabled
    if !cookies['_bookdrive_session']

      redirect_to cookies_required_path
      
    # Returning donor with existing order number
    elsif cookies['donor_' + @donor.order_number] && existing_donor = Donor.find_by_order_number( @donor.order_number )
    
      redirect_to downloads_donor_path( existing_donor )
    
    # New donor
    elsif @donor.save
      
      cookies['donor_' + @donor.order_number] = {
        :value => @donor.donor_code,
        :expires => 2.months.from_now
      }

      redirect_to( downloads_donor_path(@donor), :notice => 'Thank you for making a donation!')
      
    # Fails (most likely already exists)
    else
      render :action => "register"
    end
    
  end

  # POST /donors
  # POST /donors.xml
  def create

    @donor = Donor.new(params[:donor])
    
    respond_to do |format|
            
      if @donor.save
        format.html { redirect_to(@donor, :notice => 'Donor was successfully created!') }
        format.xml  { render :xml => @donor, :status => :created, :location => @donor }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @donor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /donors/1
  # PUT /donors/1.xml
  def update
    @donor = Donor.find_by_order_number(params[:id])

#    @donor.saving_address = true
    
    respond_to do |format|
      if @donor.update_attributes(params[:donor])
        format.html { redirect_to(@donor, :notice => 'Donor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @donor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.xml
  def destroy
    @donor = Donor.find_by_order_number(params[:id])
    
    @donor.destroy

    respond_to do |format|
      format.html { redirect_to(donors_url) }
      format.xml  { head :ok }
    end
  end

  private
  
  def sort_column
    Donor.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
  
  def cleanse_order_number
    # Clean the confirmation code before creating the donor
    params[:donor][:order_number].upcase!
    params[:donor][:order_number].gsub!(/[^0-9A-Z]/,'')
    params[:donor][:order_number].sub!(/(\d{3})-?(\d{7})-?(\d{7})/, '\1-\2-\3')    
  end
      
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/_address_form.html.erb
<%= form_for(@donor) do |f| %>
  <% if @donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
      <% @donor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
  </div>

  <div class="field">
    <%= f.label :address1 %><br />
    <%= f.text_field :address1 %>
  </div>

  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </div>

  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  
  <%= f.hidden_field :cd_requested, :value => true %>
  
  <div class="actions">
    <%= submit_tag( "Request a CD" ) %>
  </div>
<% end %>

app/views/donors/_donors.html.erb
<table id="donors_table" class="index">
  <caption style="overflow:hidden;">
  <span style="float:left;"><%= page_entries_info( @donors ).html_safe %></span>
  <%= will_paginate @donors %></caption>
  
  <thead>
  <tr>
    <th><%= sortable "order_number" %></th>
    <th><%= sortable "created_at" %></th>
    <th><%= sortable "downloads_count", "Downloads" %></th>
  </tr>
  </thead>
  
  <tfoot>
  	<tr>
  		<td colspan="8"><%= will_paginate @donors %></td>
  	</tr>
  </tfoot>
  
  <tbody>
<% @donors.each do |donor| %>
  <tr>
    <td><%= link_to '', donor_path(donor) %><%= donor.order_number %></td>
    <td><%= donor.created_at.to_formatted_s(:long) %></td>
    <td><%= donor.downloads_count %></td>
  </tr>
<% end %>
</tbody>
</table>



<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

app/views/donors/_download_location.html.erb
<div class="beware">
  <h3>Where will the downloads go?</h3>
  <p>The album will be saved in the download location set by your browser, just like any other download. If you do not know where this is, check your browser settings. A few possibilities are:</p>
    <ul><li>Desktop</li><li>Downloads Folder</li><li>Documents Folder</li></ul>
</div>

app/views/donors/_form.html.erb
<%= simple_form_for @donor do |f| %>

<%= f.input :full_name %>
<%= f.input :address1 %>
<%= f.input :address2 %>
<%= f.input :city %>
<%= f.input :state %>
<%= f.input :zip %>
<%= f.input :country, :priority => [ "United States"] %>

<p>Also please give us your email address so we can contact you should there be any problems</p>

<%= f.input :email %>

<%= f.submit :value => 'Submit' %>

<% end %>

app/views/donors/_new_form.html.erb
<h1>Thank You!</h1>

<%= snippet 'Thank You - Greeting' %>

<% if @is_mobile %>
<div class="beware">
<%= snippet 'Beware - Mobile Devices' %>
</div>

<% else %>

<div class="ordernumber">


  <div class="beware">
    <%= snippet 'Beware - Work Computer' %>
  </div>

  <div class="beware">
    <%= snippet 'Beware - Cookies Required' %>
  </div>

<%= simple_form_for @donor, :url => submit_registration_donors_path do |f| %>

  <%= f.input :order_number,
      :label => 'Enter Your Order Number Below',
      :hint => 'Each order number is only valid on one computer.',
      :input_html => {
          :maxlength => 50,
          :size => 50
      } 
  %>
  <%= f.submit 'Get Your Pomplamoose Christmas Album' %>
<% end %>
</div>
<% end %>

<% if !@is_mobile %>
<div class="email_image">
<%= image_tag 'amazon_email.png' %>
</div>

<div class="email_image">
<%= image_tag 'paypal_email.png' %>
</div>

<% end %>

app/views/donors/download_tracks.html.erb
<% title "Download Tracks" %>

<h1>Download Individual Tracks</h1>

<p><b>ONLY USE THIS PAGE IF YOU CAN'T OPEN ZIP FILES.</b><br />If you have the ability to open .zip files, go to the <b><%= link_to "ALBUM DOWNLOAD PAGE", downloads_donor_path( @donor ) %></b> and click the big green button to get the album.</p>

<%= render :partial => 'download_location' %>

  
  <p>If you do not have the ability to open .zip files, you may choose to download each .mp3 individually using the links below. Only use these links if you have not already downloaded the .zip on the previous page. They're the SAME files!</p>

  <ul class="tracks">
  <% Gift.all.each do |gift| %>
    <% if gift.name != "Pomplamoose Christmas Album" %>
      <%= content_tag :li, :id => 'track_' + gift.id.to_s + '_li', :class => 'track_link' do %>
        <%= link_to gift.name, download_donor_gift_path( @donor, gift ), :id => 'track_' + gift.id.to_s %>
      <% end %>
    <% end %>
  <% end %>
  </ul>
</p>

app/views/donors/downloads.html.erb
<% title "Downloads" %>

<h1>Download Pomplamoose's Christmas Album!</h1>

<p>Thank you for your donation! You may now download the Pomplamoose Christmas Album to your computer! Please note that this is the only computer at which you may download the album using this order number.</p>

  <%= render :partial => 'download_location' %>

<p>Click on the button below to download the entire album as a .zip file.</p>
  
  <div id="album_link" class="album_link">
    <% album = Gift.find_by_name("Pomplamoose Christmas Album") %>
    <%= link_to "Download Pomplamoose's Christmas Album", download_donor_gift_path( @donor, album ), :onclick => 'return false;' %>
  </div>
  
  <p>If you do not have the ability to open .zip files, you may choose to download each .mp3 individually. Go to the <b><%= link_to "Individual Tracks", download_tracks_donor_path( @donor ) %></b> page to download them one by one.</p>

</p>

app/views/donors/edit.html.erb
<% admin_page %>

<div class="links">
<%= link_to 'Back', @donor %>
</div>

<h1>Editing donor</h1>

<%= render 'form' %>

app/views/donors/index.html.erb
<% title "Donors" %>

<h1>Donor List</h1>
<% admin_page %>


<%= form_tag donors_path, :method => 'get', :id => "index_search", :class => "search_form" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="donors"><%= render 'donors' %></div>
<% end %>

app/views/donors/index.js.erb
$("#donors").html("<%= escape_javascript(render("donors")) %>");

app/views/donors/new.html.erb
<% title "Order Number" %>


<h1>Donor Order Number</h1>

<%= render :partial => "/donors/new_form" %>

app/views/donors/register.html.erb
<% title "Thank You" %>

<%= render :partial => "/donors/new_form" %>

app/views/donors/show.html.erb
<% title "Donor Info" %>
<% admin_page %>


<div class="links">
  <%= link_to 'Back', donors_path %> |
  <%= link_to 'Edit', edit_donor_path(@donor) %> |
  <%= link_to 'Destroy', @donor, :confirm => 'Are you sure?', :method => :delete %>
</div>

<table>
  <tr><td>Id</td><td><%= @donor.id %></td></tr>
  <tr><td>Order Number</td><td><%= @donor.order_number %></td></tr>
  <tr><td>Registration Date</td><td><%= @donor.created_at.to_formatted_s(:long) %></td></tr>
  <tr><td>Downloads</td><td>
  <% @donor.download_events.each do |download| %>
    <%= download.gift_id %>: <%= download.gift.name %><br />
  <% end %>
  </td></tr>
</table>