config/routes.rb
Bookdrive::Application.routes.draw do

  match 'staff' => 'pages#staff', :as => :staff
  match 'staff' => 'pages#staff', :as => 'user_root'

  scope "/staff" do
    resources :snippets
    resources :schools
    resources :books do
      resources :copies
      collection do
        get 'update_wishlist'
      end
    end

    devise_for :users, :path => '', :path_names => { :sign_in => 'login', :sign_out => 'logout' }
    resources :users
  
    resources :gifts
    resources :download_events
    resources :donors
    resources :articles
    resources :questions
  
  end

  resources :donors do
    resources :gifts do
      member do
        get 'download'
      end
    end
    member do
      get 'downloads'
      get 'download_tracks'
    end
    collection do
      get 'register'
      post 'submit_registration'
    end
  end

  match 'library' => 'pages#library', :as => :library
  match 'offsite' => 'pages#offsite', :as => :offsite
  match 'oops' => 'pages#oops', :as => :oops
  match 'cookies_required' => 'pages#cookies_required', :as => :cookies_required
  match 'press' => 'pages#press', :as => :press
  match 'thankyou' => 'pages#thankyou', :as => :thankyou
  match 'usedbooks' => 'pages#usedbooks', :as => :usedbooks
  match 'about' => 'pages#about', :as => :about
  match 'faq' => 'pages#faq', :as => :faq
  match '' => 'pages#home', :as => :home
  root :to => 'pages#home'
  

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :content
  
  def self.search(search)
    if search
      where('name ILIKE ?', "%#{search}%")
    else
      scoped
    end
  end
  
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  
  filter_access_to :all

  cache_sweeper :snippet_sweeper

  helper_method :sort_column, :sort_direction
  
  
  # GET /snippets
  # GET /snippets.xml
  def index
    @snippets = Snippet.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 25, :page => params[:page])
  end

  # GET /snippets/1
  # GET /snippets/1.xml
  def show
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @snippet }
    end
  end

  # GET /snippets/new
  # GET /snippets/new.xml
  def new
    @snippet = Snippet.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @snippet }
    end
  end

  # GET /snippets/1/edit
  def edit
    @snippet = Snippet.find(params[:id])
  end

  # POST /snippets
  # POST /snippets.xml
  def create
    @snippet = Snippet.new(params[:snippet])

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to(@snippet, :notice => 'Snippet was successfully created.') }
        format.xml  { render :xml => @snippet, :status => :created, :location => @snippet }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @snippet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /snippets/1
  # PUT /snippets/1.xml
  def update
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      if @snippet.update_attributes(params[:snippet])
        format.html { redirect_to(@snippet, :notice => 'Snippet was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @snippet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.xml
  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy

    respond_to do |format|
      format.html { redirect_to(snippets_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def sort_column
    Snippet.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/snippets/_form.html.erb
<%= simple_form_for(@snippet) do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inputs">
    <%= f.input :name %>
    <%= f.input :content,
        :input_html => {
            :rows => 10
        } %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/snippets/_snippets.html.erb
<table id="snippets_table" class="index">
  <caption style="overflow:hidden;">
  <span style="float:left;"><%= page_entries_info( @snippets ).html_safe %></span>
  <%= will_paginate @snippets %></caption>
	
  <thead>
  <tr>
    <th><%= sortable 'id' %></th>
    <th><%= sortable 'name' %></th>
    <th><%= sortable 'created_at' %></th>
  </tr>
  </thead>

  <tfoot>
  	<tr>
  		<td colspan="8"><%= will_paginate @snippets %></td>
  	</tr>
  </tfoot>

  <tbody>
<% @snippets.each do |snippet| %>
  <tr>     
    <td><%= link_to '', snippet_path(snippet) %><%= snippet.id %></td>
    <td><%= snippet.name %></td>
    <td><%= snippet.created_at.to_formatted_s(:long) %></td>
  </tr>
<% end %>
</tbody>
</table>


<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

app/views/snippets/edit.html.erb
<% title "Snippets &raquo; " + @snippet.name + " &raquo; Edit" %>
<% admin_page %>

<div class="links">
<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>
</div>

<h1>Editing snippet</h1>

<%= render 'form' %>

app/views/snippets/inde.js.erb
$("#snippets").html("<%= escape_javascript(render("snippets")) %>");

app/views/snippets/index.html.erb
<% title "Snippets" %>
<% admin_page %>


<div class="links">
  <%= link_to 'New Snippet', new_snippet_path %>
</div>

<h1>Snippets</h1>


<%= form_tag questions_path, :method => 'get', :id => "index_search", :class => "search_form" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="snippets"><%= render 'snippets' %></div>
<% end %>

app/views/snippets/new.html.erb
<% title "Snippets &raquo; New" %>
<% admin_page %>


<div class="links">
<%= link_to 'Back', snippets_path %>
</div>

<h1>New snippet</h1>

<%= render 'form' %>

app/views/snippets/show.html.erb
<% title "Snippet &raquo; " + @snippet.name %>
<% admin_page %>

<div class="links">  
  <%= link_to 'Edit', edit_snippet_path(@snippet) %> |
  <%= link_to 'Back', snippets_path %>
</div>

<h1><%= @snippet.name %></h1>

<%= @snippet.content %>