config/routes.rb
Bookdrive::Application.routes.draw do

  match 'staff' => 'pages#staff', :as => :staff
  match 'staff' => 'pages#staff', :as => 'user_root'

  scope "/staff" do
    resources :snippets
    resources :schools
    resources :books do
      resources :copies
      collection do
        get 'update_wishlist'
      end
    end

    devise_for :users, :path => '', :path_names => { :sign_in => 'login', :sign_out => 'logout' }
    resources :users
  
    resources :gifts
    resources :download_events
    resources :donors
    resources :articles
    resources :questions
  
  end

  resources :donors do
    resources :gifts do
      member do
        get 'download'
      end
    end
    member do
      get 'downloads'
      get 'download_tracks'
    end
    collection do
      get 'register'
      post 'submit_registration'
    end
  end

  match 'library' => 'pages#library', :as => :library
  match 'offsite' => 'pages#offsite', :as => :offsite
  match 'oops' => 'pages#oops', :as => :oops
  match 'cookies_required' => 'pages#cookies_required', :as => :cookies_required
  match 'press' => 'pages#press', :as => :press
  match 'thankyou' => 'pages#thankyou', :as => :thankyou
  match 'usedbooks' => 'pages#usedbooks', :as => :usedbooks
  match 'about' => 'pages#about', :as => :about
  match 'faq' => 'pages#faq', :as => :faq
  match '' => 'pages#home', :as => :home
  root :to => 'pages#home'
  

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates_presence_of :title
  
  validates_numericality_of :amazon_price, :greater_than_or_equal_to => 0, :allow_blank => true
  validates_numericality_of :copies_desired, :greater_than_or_equal_to => 0, :only_integer => true
  validates_numericality_of :copies_received, :greater_than_or_equal_to => 0, :only_integer => true
  
  has_many :copies, :dependent => :destroy
  belongs_to :user
  
  accepts_nested_attributes_for :copies, :allow_destroy => true
  
  before_save :calculate_dollars
  before_create :calculate_dollars
  before_save :calculate_total_book_count
  before_create :calculate_total_book_count
  before_save :determine_complete
  before_create :determine_complete
  before_save :determine_set
  before_create :determine_set
  before_save :trim_refs_from_urls
  before_create :trim_refs_from_urls
  
  def update_from_wl_book(wl_book)
    wl_book.attribute_hash().each do |key,value|
      
      old_value = send(key)
      
      if key.to_s == 'amazon_wl_add_date'
        if  old_value.to_formatted_s(:long).sub(/\s\s/,' ') != value.to_s
          logger.debug 'add_date: ' + old_value.to_formatted_s(:long).sub(/\s\s/,' ')
          logger.debug 'add_date: ' + value.to_s + "\n"
          send(key+'=',value)
        end
      elsif old_value.to_s != value.to_s
        logger.debug key + ': ' + old_value.to_s
        logger.debug key + ': ' + value.to_s + "\n"
        send(key+'=',value)
      end
    end
  end
  
  def self.search(search)
    if search
      where('title ILIKE ? OR author ILIKE ?', "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end
  
  private
  
  def determine_set
    if self.title =~ /Books 1(?:-| to )(\d+)/ || self.title =~ /(\d+) Book Box Set/
      self.books_in_set = $1
    end    
  end
  
  def determine_complete
    if self.copies_received >= self.copies_desired
      self.copies_complete = true
    end
  end
  
  def calculate_dollars  
    copies = self.copies_delivered > self.copies_received ? self.copies_delivered : self.copies_received
    price = self.amazon_price && self.amazon_price > 0.00 ? self.amazon_price : 0.00
    self.dollars_donated = self.amazon_price.to_f * copies.to_i
  end

  def calculate_total_book_count
    copies = self.copies_delivered > self.copies_received ? self.copies_delivered : self.copies_received
    self.total_book_count = self.books_in_set * copies
  end
  
  def trim_refs_from_urls
    if self.amazon_product_url.present?
      self.amazon_product_url.sub!(/ref=.+?\/[\d\-]+/,'')
    end
    if self.amazon_wl_cart_url.present?
      self.amazon_wl_cart_url.sub!(/ref=.+?\/[\d\-]+/,'')
    end
  end  
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  require 'update_wishlist.rb'
  require 'net/http'
  
  filter_access_to :all
  
  before_filter :load_book_from_amazon, :only => :create
  
  helper_method :sort_column, :sort_direction

  
  def update_wishlist
    @@logger = logger
    @wl_books = AmazonWishListFetcher.new.get_updated_wl_books()
    
    @books = Book.all
    @books_map = Hash.new
    @books.each do |b|
      book_identifier = b.title

      if b.author.present?
        book_identifier = b.author + '-' + book_identifier
      end
      
      if b.amazon_product_url.present?
        book_identifier = b.amazon_product_url
        book_identifier.sub!(/ref=wl_it_dp_v\/[\d\-]+/,'')
      end
      
      @books_map[book_identifier] = b
    end
    
    @wl_books.each do |wl_book|
      wl_book_identifier = wl_book.title

      if wl_book.author != nil
        wl_book_identifier = wl_book.author + '-' + wl_book_identifier
      end

      if wl_book.amazon_product_url != nil
        wl_book_identifier = wl_book.amazon_product_url
        wl_book_identifier.sub!(/ref=wl_it_dp_v\/[\d\-]+/,'')
      end
      
      if @books_map.include?(wl_book_identifier)
        book = @books_map[wl_book_identifier]
        book.update_from_wl_book(wl_book)
        if book.changed?
          logger.debug "UPDATE: " + book.title
          book.save
        end
      else
        create_book_from_wl(wl_book)
      end
    end
    
    # Expire the home page after the wish list has been updated
    expire_page(:controller => 'pages', :action => 'home')
    expire_fragment('bookstats')
    
    redirect_to books_path, :notice => 'Updated books from the Amazon Wish List'
  end

  # GET /books
  # GET /books.xml
  def index
    @books = Book.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 25, :page => params[:page])
  end

  # GET /books/1
  # GET /books/1.xml
  def show
    @book = Book.find(params[:id])
    @copy = Copy.new(:user => current_user)
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @book }
    end
  end

  # GET /books/new
  # GET /books/new.xml
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.xml
  def create
    
    if @book == nil
      @book = Book.new(params[:book])
    end

    @book.source = current_user
    
    respond_to do |format|
      if @book.save
        format.html { redirect_to(@book, :notice => 'Book was successfully created.') }
        format.xml  { render :xml => @book, :status => :created, :location => @book }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.xml
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to(@book, :notice => 'Book was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.xml
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to(books_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def sort_column
    Book.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
  def create_book_from_wl(wl_book)    
    @new_book = Book.new( wl_book.attribute_hash() )
    @new_book.source = 'Wish List'
    logger.debug "CREATE: " + @new_book.title
    logger.debug @new_book.inspect
    if ! @new_book.save
      logger.debug  @new_book.errors
    end
  end
  
  def load_book_from_amazon
    logger.debug 'running before filter'
    
    return if (params[:book][:title] && !params[:book][:title].length == 0) || params[:book][:amazon_product_url].blank?

    logger.debug 'Going to load book from amazon'
    @book = Book.new
    
    url = params[:book][:amazon_product_url].sub(/\/ref=.+?coliid=([A-Z0-9]+)\&.+/,'/?ie=UTF8&coliid=\1&colid=1WJWNVAVRKJVO')
    html = Net::HTTP.get_response(URI.parse(url)).body
    
    @book.amazon_product_url = url
    
    matches = html.match(/<h1 class="parseasinTitle"><span id="btAsinTitle" style="">([^<]+)\s*(?:<span style="text-transform:capitalize; font-size: 16px;">([^<]+)<\/span>)?<\/span><\/h1>/)
    if matches && matches.length > 0
      @book.title = matches[1]
      @book.amazon_cover_type = matches[2]
      @book.amazon_cover_type.gsub!(/[\[\(\]\)]/,'')
    end
        
    matches = html.match(/<td><span\s+class="listprice">\$([\d\.]+)<\/span><\/td>/)
    if matches && matches.length > 0
      @book.amazon_strike_price = matches[1]
    end

    matches = html.match(/>([^<]+)<\/a>.+?\(Author\)/)
    if matches && matches.length > 0
      @book.author = matches[1]
    end

    matches = html.match(/<td><b\s+class="priceLarge">\$([\d\.]+)<\/b>/)
    if matches && matches.length > 0
      @book.amazon_price = matches[1]
    end

    matches = html.match(/<div class="buying" style="padding-bottom: 0.75em;">\s*<span class="avail[^"]*?">([^<]+)<\/span>/)
    if matches && matches.length > 0
      @book.amazon_availability = matches[1]
      @book.amazon_availability.sub!(/.$/,'')    
    end
    
    matches = html.match(/Ships from and sold by <b>([^<]+)<\/b>/)
    if matches && matches.length > 0
      @book.amazon_merchant = matches[1]
    end
    
    matches = html.match(/src="([^"]+)" id="prodImage"/)
    if matches && matches.length > 0
      @book.amazon_image_url = matches[1]
      @book.amazon_image_original_url = @book.amazon_image_url.sub(/(.+I\/[^\.]+)\..+/,'\1.jpg')
      @book.amazon_image_url.sub!(/_PIsitb-.+?,-[\d]+/,'')
    end

  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books.html.erb
<table id="books_table" class="index">
  <caption style="overflow:hidden;">
  <span style="float:left;"><%= page_entries_info( @books ).html_safe %></span>
  <%= will_paginate @books %></caption>
	
  <thead>
  <tr>
    <th><%= sortable 'title' %></th>
    <th><%= sortable 'author' %></th>
    <th><%= sortable 'amazon_cover_type', 'Cover' %></th>
    <th><%= sortable 'amazon_price', 'Price' %></th>
    <th><%= sortable 'amazon_wl_priority', 'Priority' %></th>
    <th><%= sortable 'books_in_set', 'Set' %></th>
  </tr>
  </thead>

  <tfoot>
  	<tr>
  		<td colspan="8"><%= will_paginate @books %></td>
  	</tr>
  </tfoot>

  <tbody>
<% @books.each do |book| %>
  <tr>
    <td><%=  link_to '', book_path(book) %><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.amazon_cover_type %></td>
    <td><%= number_to_currency book.amazon_price %></td>
    <td><%= book.amazon_wl_priority %></td>
    <td><%= book.books_in_set %></td>
  </tr>
<% end %>
</tbody>
</table>


<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inputs">
    
    <%= f.input :amazon_product_url, :label => "Amazon Product URL", :hint => "Must be the URL linked from the wish list", :input_html => { :size => 100 } %>
  
    <%= f.input :title, :hint => "Will be extracted from Amazon if left blank" %>

    <%= f.input :author, :hint => "Full name in regular order (first-name last-name)" %>

    <%= f.input :amazon_cover_type, :label => "Cover Type", :hint => "(e.g. Paperback, Hardcover, etc.)" %>


    <div style="overflow:hidden;">
    <div style="float:left;width:23%;">
    <%= f.input :amazon_price, :hint => "In US Dollars", :input_html => { :default => 0, :min => 0, :max => 9999, :step => 0.01, :maxlength => 6, :size => 10  } %>
    </div>

    <div style="float:left;width:23%;margin-right: 5%">
    <%= f.input :amazon_strike_price, :hint => "This is the original price.", :input_html => { :default => 0, :min => 0, :max => 9999, :step => 0.01, :maxlength => 6, :size => 10  } %>
    </div>

    <div style="float:left;width:23%;margin-right: 5%">
    <%= f.input :books_in_set, :hint => "If a box set, how many books are in the set?", :input_html => { :default => 0, :min => 0, :max => 100, :step => 1, :maxlength => 3, :size => 4  } %>
    </div>
    </div>
    
    <!--
    <div style="overflow:hidden;">
    <div style="float:left;width:20%;margin-right: 5%">
    <%= f.input :copies_desired, :label => "Copies Desired", :hint => "Requested on the Wish List", :input_html => { :min => 0, :max => 9999, :step => 1, :maxlength => 4, :size => 5 } %>
    </div>
    
    <div style="float:left;clear:right;width:20%;">
    <%= f.input :copies_received, :label => "Copies Received", :hint => "Donated per the Wish List (not shipments received)", :input_html => { :min => 0, :max => 9999, :step => 1, :maxlength => 4, :size => 5 } %>
    </div>
    </div>
  -->

    <%= f.input :amazon_wl_cart_url, :label => "Amazon Add to Cart URL", :hint => "Must be the URL linked from the wish list" %>

    <%= f.input :amazon_image_url, :label => "Amazon Image URL", :hint => "Copy from the image on the product page" %>


  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<% title "Books &raquo; " + @book.title + " &raquo; Edit" %>
<% admin_page %>


<div class="links">
<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>
</div>

<h1>Editing book</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<% title "Books" %>
<% admin_page %>

<% cache 'bookstats' do %>

<div class="statbox bookstats">
  <h3>Titles</h3>
  <ul class="list">
    <li><span>Unique Titles</span> <em><%= number_with_delimiter Book.count(:title) %></em></li>
    <li><span>Titles Complete</span> <em><%= number_with_delimiter Book.where("copies_complete=?",true).count(:title) %></em></li>
    <li><span>Titles Available</span> <em><%= number_with_delimiter Book.where("copies_complete=?",false).count(:title) %></em></li>
  </ul>
</div>

<div class="statbox bookstats">
  <h3>Books and Dollars</h3>
  <ul class="list">
    <li><span>Total Books</span> <em><%= number_with_delimiter Book.sum(:total_book_count) %></em></li>
    <li><span>Total Dollars</span> <em><%= number_to_currency Book.sum(:dollars_donated) %></em></li>
    <li><span>Dollars per Donor</span> <em><%= number_to_currency( Book.sum(:dollars_donated) / Donor.count ) %></em></li>
  </ul>
</div>

<% end %>


<div class="links">
  <%= link_to 'New Book', new_book_path %>
</div>

<h1>Book List</h1>


<%= form_tag books_path, :method => 'get', :id => "index_search", :class => "search_form" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="books"><%= render 'books' %></div>
<% end %>

app/views/books/index.js.erb
$("#books").html("<%= escape_javascript(render("books")) %>");
document.title = "Richmond Book Drive » " + "<%= escape_javascript("#{params[:search].to_s.titleize} Books by #{(params[:sort] || 'title').titleize} - Page #{params[:page] || 1}") %>";

app/views/books/new.html.erb
<% title "Books &raquo; New" %>
<% admin_page %>

<div class="links">
<%= link_to 'Back', books_path %>
</div>

<h1>New book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<% title "Books &raquo; " + @book.title %>
<% admin_page %>


<div style="overflow: hidden;">
<div class="links" style="float: left;">
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>
</div>

<div style="float: right">
<%= form_tag books_path, :method => 'get', :id => "books_search_remote", :class => "search_form_remote" do %>
  <p>
    <%= text_field_tag :search, params[:search],
        :style => "padding: 3px 5px; margin-left: 15px; font-size: 108%;"
    %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
</div>
</div>

<div class="show_book">

<% if @book.amazon_image_original_url.present? %>
  <%= image_tag @book.amazon_image_original_url, :class => 'book_cover', :alt => @book.title %>
<% end %>


<h1><%= @book.title %></h1>
<% if @book.author.present? %>
<h2><%= @book.author %></h2>
<% end %>


<div class="left">

<div class="statbox wishlist">
  <h3>Wish List Status</h3>
  <ul class="list">
    <li><span>Complete</span> <em><%= @book.copies_desired > 0 && @book.copies_received >= @book.copies_desired  ? "Yes" : "No" %></em></li>
    <li><span>Desired</span> <em><%= @book.copies_desired %></em></li>
    <li><span>Received</span> <em><%= @book.copies_received %></em></li>
    <li><span>Delivered</span> <em><%= @book.copies_delivered %></em></li>
    <li><span>Total Books</span> <em><%= @book.total_book_count %></em></li>
    <li><span>Dollars</span> <em><%= number_to_currency @book.dollars_donated %></em></li>
  </ul>
</div>

<div class="statbox copies">
  <h3>Copies Delivered</h3>
  <%= simple_form_for @copy, :url => book_copies_path(@book) do |f| %>
    <div class="actions copy_actions" style="overflow: hidden;">
      
      <div style="float: left; margin: 0;padding: 0;">
        <%= f.input :copy_count,
            :collection => 1..99,
        %>
      </div>
      
      <div style="float: left; margin: 2px 0 0 5px;padding: 0;">
        <%= f.button :submit,
            :value => "Copies Delivered"
        %>
      </div>
    
    </div>
  <% end %>
  <ul class="list">
    <% @book.copies.joins(:user).order("created_at DESC").each do |copy| %>
    <li><span><%= copy.created_at.to_formatted_s(:mdhm) %></span> <em><%= copy.user.email.sub(/\@.+/,'').slice(0,10) %> <%= link_to '[x]', book_copy_path(@book, copy), :confirm => 'Are you sure?', :method => :delete %></em></li>
    <% end %>
  </ul>
</div>

</div>



<div class="book_info">
  <div class="statbox">
  <h3>Amazon Info</h3>

  <ul class="list">
    <li><span>Merchant</span> <em><%= @book.amazon_merchant %></em></li>
    <li><span>Price</span> <em class="price"><%= number_to_currency @book.amazon_price %>
    <% if @book.amazon_strike_price.present? %>
      <strong class="strike_price">(<strike><%= number_to_currency @book.amazon_strike_price %></strike>)</strong>
    <% end %>
    </em>
    </li>
    <li><span>Cover</span> <em><%= @book.amazon_cover_type %></em></li>
    <li><span>Books in Set</span> <em><%= @book.books_in_set %></em></li>
    <li><span>Availability</span> <em><%= @book.amazon_availability %></em></li>
    <% if @book.amazon_product_url.present? %><li><%= link_to 'Amazon Product Page', @book.amazon_product_url %></li><% end %>
    <% if @book.amazon_wl_cart_url.present? %><li><%= link_to 'Amazon Add to Cart', @book.amazon_wl_cart_url %></li><% end %>

  </ul>

  </div>



  <div class="statbox">
  <h3>Wish List</h3>
  <ul>
  <li><span>Added</span> <% if @book.amazon_wl_add_date.present? %><em><%= @book.amazon_wl_add_date.to_formatted_s(:long) %></em><% end %></li>
  <li><span>Priority</span> <% if @book.amazon_wl_priority.present? %><em><%= @book.amazon_wl_priority %></em><% end %></li>
  <li><span>Comment</span> <% if @book.amazon_wl_comment.present? %><em class="comment"><%= @book.amazon_wl_comment %></em><% end %></li>
  </div>

</div>


</div>