config/routes.rb
Bookdrive::Application.routes.draw do

  match 'staff' => 'pages#staff', :as => :staff
  match 'staff' => 'pages#staff', :as => 'user_root'

  scope "/staff" do
    resources :snippets
    resources :schools
    resources :books do
      resources :copies
      collection do
        get 'update_wishlist'
      end
    end

    devise_for :users, :path => '', :path_names => { :sign_in => 'login', :sign_out => 'logout' }
    resources :users
  
    resources :gifts
    resources :download_events
    resources :donors
    resources :articles
    resources :questions
  
  end

  resources :donors do
    resources :gifts do
      member do
        get 'download'
      end
    end
    member do
      get 'downloads'
      get 'download_tracks'
    end
    collection do
      get 'register'
      post 'submit_registration'
    end
  end

  match 'library' => 'pages#library', :as => :library
  match 'offsite' => 'pages#offsite', :as => :offsite
  match 'oops' => 'pages#oops', :as => :oops
  match 'cookies_required' => 'pages#cookies_required', :as => :cookies_required
  match 'press' => 'pages#press', :as => :press
  match 'thankyou' => 'pages#thankyou', :as => :thankyou
  match 'usedbooks' => 'pages#usedbooks', :as => :usedbooks
  match 'about' => 'pages#about', :as => :about
  match 'faq' => 'pages#faq', :as => :faq
  match '' => 'pages#home', :as => :home
  root :to => 'pages#home'
  

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { ' &raquo; '.html_safe + page_title.to_s.html_safe }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end

  def admin_page
    @is_admin_page = true
  end
  
  def admin_page?
    @is_admin_page
  end

  def hold_flash_notices
    @hold_flash_notices = true
  end
  
  def hold_flash_notices?
    @hold_flash_notices
  end
  
  
  
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
  
  def tab_for(name, options, condition=nil)
    condition = current_page?(options) if condition.nil?
    link_to_unless(condition, name, options) do
      content_tag(:span, name)
    end
  end
  
  def link_away(title, url)
    #link_to title, offsite_path(:p_title => title, :p_url => url), :target => '_blank'
    link_to title, url, :target => '_blank', :onclick => "recordOutboundLink(this, 'Outbound Links', '" + url + "');return false;"
  end
  
  def snippet(name)
    snip = Snippet.find_by_name(name)
    if snip != nil && snip.content.present?
      snip.content.html_safe
    else
      ""
    end
  end

end

app/views/layouts/_adminbar.html.erb
<div class="admin">
  
  <em>Admin Bar</em>
  
  <div class="nav">
    <%= tab_for "Overview", staff_path %>
    <% if permitted_to? :manage, :press %>
      <%= tab_for "Articles", articles_path %>
    <% end %>
    <% if permitted_to? :manage, :books %>
      <%= tab_for "Books", books_path %>
    <% end %>
    <% if permitted_to? :manage, :donors %>
      <%= tab_for "Donors", donors_path %>
    <% end %>
    <% if permitted_to? :manage, :questions %>
      <%= tab_for "Questions", questions_path %>
    <% end %>
    <% if permitted_to? :manage, :schools %>
      <%= tab_for "Schools", schools_path %>
    <% end %>
    <% if permitted_to? :manage, :snippets %>
      <%= tab_for "Snippets", snippets_path %>
    <% end %>
    <% if permitted_to? :manage, :users %>
      <%= tab_for "Users", users_path %>
    <% end %>
    <strong>
      <%= tab_for "Logout", destroy_user_session_path %>
    </strong>
  </div>


</div>

app/views/layouts/_analytics.html.erb
<%
  # Use QA account by default
  @ga_account = 'UA-661691-7'

  # Prod account if rails_env is production
  if ENV['RAILS_ENV'] == 'production'
    @ga_account = 'UA-661691-6'
  end
%>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= @ga_account %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_assets.html.erb
<%= include_stylesheets :screen, :media => 'screen' %>

<%= include_javascripts :workspace %>

app/views/layouts/_footer.html.erb
<div id="footer">
  ©2010 richmondbookdrive.com
</div>

app/views/layouts/_header.html.erb
<div id="header">

  <div class="title transparent">
    <%= link_to content_tag('h1', 'Richmond Book Drive'), '/' %>
    <h2>Ignite a student's love of reading by donating great books!</h2>
  </div>

  <div class="nav">
    <%= tab_for "Home", root_path %>
    <%= tab_for "About", about_path %>
    <%= tab_for "FAQ", faq_path %>
    <%= tab_for "Press", press_path %>
    <%= tab_for "Used Books", usedbooks_path %>
    <%= tab_for "Thank You", thankyou_path %>
  </div>

</div>

<% if user_signed_in? && admin_page? %>
  <%= render 'layouts/adminbar' %>
<% end %>

<% unless hold_flash_notices? %>
  <% if notice %>
  <p class="notice"><%= notice %></p>
  <% end %>

  <% if alert %>
  <p class="alert"><%= alert %></p>
  <% end %>
<% end %>

app/views/layouts/_paypal_button.html.erb
<div class="paypal_button">
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" onsubmit="recordDonateButtonClick('<%= donatebutton_page %>')">
<input type="hidden" name="cmd" value="_donations">
<input type="hidden" name="business" value="richmondbookdrive@gmail.com">
<input type="hidden" name="lc" value="US">
<input type="hidden" name="item_name" value="Richmond Book Drive">
<input type="hidden" name="no_note" value="0">
<input type="hidden" name="currency_code" value="USD">
<input type="hidden" name="bn" value="PP-DonationsBF:btn_donateCC_LG.gif:NonHostedGuest">
<input type="image" src="https://www.paypal.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" style="display: none;">
</form>
</div>

app/views/layouts/_thermometer.html.erb
<div class="thermometer">
  <div style="float:left;width:250px;">    
  <img alt='Progress' src='http://www.fundraiserinsight.org/libs/thermometer.php?current=<%= snippet 'Library - Donations To Date' %>&max=<%= snippet 'Library - Donation Goal' %>&curr=36&t_id=0&skin=small_hor' border='0' style="position: absolute; clip: rect(1px 250px 35px 0);" />&nbsp;
  </div>
  <span><%= number_to_currency snippet('Library - Donation Goal'), :precision => 0 %> Goal</span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  
  <title>Richmond Book Drive<%= yield(:title) %></title>
    
  <%= render 'layouts/assets' %>

  <%= yield :head %>

  <%= csrf_meta_tag %>

  <% if !user_signed_in? || hold_flash_notices %>
    <%= render 'layouts/analytics' %>
  <% end %>
    
</head>
<body>

  <div class="container <% if admin_page? %>admin_container<% end %>">

    <%= render 'layouts/header' %>
        
    <%= yield :video %>

    <%= yield :library %>
    
    <div id="section">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
    
  </div>
  
</body>
</html>